choices = (
    ("Environment____Console",
        "Environment :: Console"),
    ("Environment____Handhelds_PDA_s",
        "Environment :: Handhelds/PDA's"),
    ("Environment____MacOS_X",
        "Environment :: MacOS X"),
    ("Environment____No_Input_Output__Daemon",
            "Environment :: No Input/Output (Daemon)"),
    ("Environment____Other_Environment",
        "Environment :: Other Environment"),
    ("Environment____Plugins",
        "Environment :: Plugins"),
    ("Environment____Web_Environment",
        "Environment :: Web Environment"),
    ("Environment____Win32__MS_Windows",
        "Environment :: Win32 (MS Windows)"),
    ("Environment____X11_Applications",
        "Environment :: X11 Applications"),
    ("Framework____BFG",
        "Framework :: BFG"),
    ("Framework____Buildout", "Framework :: Buildout"),
    ("Framework____Chandler", "Framework :: Chandler"),
    ("Framework____CherryPy", "Framework :: CherryPy"),
    ("Framework____CubicWeb", "Framework :: CubicWeb"),
    ("Framework____Django", "Framework :: Django"),
    ("Framework____IDLE", "Framework :: IDLE"),
    ("Framework____Paste", "Framework :: Paste"),
    ("Framework____Plone", "Framework :: Plone"),
    ("Framework____Pylons", "Framework :: Pylons"),
    ("Framework____Setuptools_Plugin", "Framework :: Setuptools Plugin"),
    ("Framework____Trac", "Framework :: Trac"),
    ("Framework____Tryton", "Framework :: Tryton"),
    ("Framework____TurboGears", "Framework :: TurboGears"),
    ("Framework____Twisted", "Framework :: Twisted"),
    ("Framework____ZODB", "Framework :: ZODB"),
    ("Framework____Zope2", "Framework :: Zope2"),
    ("Framework____Zope3", "Framework :: Zope3"),
    ("Intended_Audience____Customer_Service",
        "Intended Audience :: Customer Service"),
    ("Intended_Audience____Developers", "Intended Audience :: Developers"),
    ("Intended_Audience____Education", "Intended Audience :: Education"),
    ("Intended_Audience____End_Users_Desktop",
        "Intended Audience :: End Users/Desktop"),
    ("Intended_Audience____Financial_and_Insurance_Industry",
        "Intended Audience :: Financial and Insurance Industry"),
    ("Intended_Audience____Healthcare_Industry",
        "Intended Audience :: Healthcare Industry"),
    ("Intended_Audience____Information_Technology",
        "Intended Audience :: Information Technology"),
    ("Intended_Audience____Legal_Industry",
        "Intended Audience :: Legal Industry"),
    ("Intended_Audience____Manufacturing",
        "Intended Audience :: Manufacturing"),
    ("Intended_Audience____Other_Audience",
        "Intended Audience :: Other Audience"),
    ("Intended_Audience____Religion", "Intended Audience :: Religion"),
    ("Intended_Audience____Science_Research",
        "Intended Audience :: Science/Research"),
    ("Intended_Audience____System_Administrators",
        "Intended Audience :: System Administrators"),
    ("Intended_Audience____Telecommunications_Industry",
        "Intended Audience :: Telecommunications Industry"),
    ("Operating_System____BeOS", "Operating System :: BeOS"),
    ("Operating_System____MacOS", "Operating System :: MacOS"),
    ("Operating_System____Microsoft", "Operating System :: Microsoft"),
    ("Operating_System____OS_2", "Operating System :: OS/2"),
    ("Operating_System____OS_Independent",
        "Operating System :: OS Independent"),
    ("Operating_System____Other_OS", "Operating System :: Other OS"),
    ("Operating_System____PalmOS", "Operating System :: PalmOS"),
    ("Operating_System____PDA_Systems", "Operating System :: PDA Systems"),
    ("Operating_System____POSIX", "Operating System :: POSIX"),
    ("Topic____Adaptive_Technologies", "Topic :: Adaptive Technologies"),
    ("Topic____Artistic_Software", "Topic :: Artistic Software"),
    ("Topic____Communications", "Topic :: Communications"),
    ("Topic____Database", "Topic :: Database"),
    ("Topic____Desktop_Environment", "Topic :: Desktop Environment"),
    ("Topic____Documentation", "Topic :: Documentation"),
    ("Topic____Education", "Topic :: Education"),
    ("Topic____Games_Entertainment", "Topic :: Games/Entertainment"),
    ("Topic____Home_Automation", "Topic :: Home Automation"),
    ("Topic____Internet", "Topic :: Internet"),
    ("Topic____Multimedia", "Topic :: Multimedia"),
    ("Topic____Office_Business", "Topic :: Office/Business"),
    ("Topic____Other_Nonlisted_Topic", "Topic :: Other/Nonlisted Topic"),
    ("Topic____Printing", "Topic :: Printing"),
    ("Topic____Religion", "Topic :: Religion"),
    ("Topic____Scientific_Engineering", "Topic :: Scientific/Engineering"),
    ("Topic____Security", "Topic :: Security"),
    ("Topic____Sociology", "Topic :: Sociology"),
    ("Topic____Software_Development", "Topic :: Software Development"),
    ("Topic____System", "Topic :: System"),
    ("Topic____Terminals", "Topic :: Terminals"),
    ("Topic____Text_Editors", "Topic :: Text Editors"),
    ("Topic____Text_Processing", "Topic :: Text Processing"),
    ("Topic____Utilities", "Topic :: Utilities"),
)

classifiers = (
    ("Development_Status____1___Planning",
        "Development Status :: 1 - Planning"),
    ("Development_Status____2___Pre-Alpha",
        "Development Status :: 2 - Pre-Alpha"),
    ("Development_Status____3___Alpha", "Development Status :: 3 - Alpha"),
    ("Development_Status____4___Beta", "Development Status :: 4 - Beta"),
    ("Development_Status____5___Production/Stable",
        "Development Status :: 5 - Production/Stable"),
    ("Development_Status____6___Mature", "Development Status :: 6 - Mature"),
    ("Development_Status____7___Inactive",
        "Development Status :: 7 - Inactive"),
    ("Environment____Console", "Environment :: Console"),
    ("Environment____Console____Curses", "Environment :: Console :: Curses"),
    ("Environment____Console____Framebuffer",
        "Environment :: Console :: Framebuffer"),
    ("Environment____Console____Newt", "Environment :: Console :: Newt"),
    ("Environment____Console____svgalib", "Environment :: Console :: svgalib"),
    ("Environment____Handhelds_PDA_s", "Environment :: Handhelds/PDA's"),
    ("Environment____MacOS_X", "Environment :: MacOS X"),
    ("Environment____MacOS_X____Aqua", "Environment :: MacOS X :: Aqua"),
    ("Environment____MacOS_X____Carbon", "Environment :: MacOS X :: Carbon"),
    ("Environment____MacOS_X____Cocoa", "Environment :: MacOS X :: Cocoa"),
    ("Environment____No_Input_Output__Daemon",
        "Environment :: No Input/Output (Daemon)"),
    ("Environment____Other_Environment", "Environment :: Other Environment"),
    ("Environment____Plugins", "Environment :: Plugins"),
    ("Environment____Web_Environment", "Environment :: Web Environment"),
    ("Environment____Web_Environment____Buffet",
        "Environment :: Web Environment :: Buffet"),
    ("Environment____Web_Environment____Mozilla",
        "Environment :: Web Environment :: Mozilla"),
    ("Environment____Web_Environment____ToscaWidgets",
        "Environment :: Web Environment :: ToscaWidgets"),
    ("Environment____Win32__MS_Windows",
        "Environment :: Win32 (MS Windows)"),
    ("Environment____X11_Applications", "Environment :: X11 Applications"),
    ("Environment____X11_Applications____Gnome",
        "Environment :: X11 Applications :: Gnome"),
    ("Environment____X11_Applications____GTK",
        "Environment :: X11 Applications :: GTK"),
    ("Environment____X11_Applications____KDE",
        "Environment :: X11 Applications :: KDE"),
    ("Environment____X11_Applications____Qt",
        "Environment :: X11 Applications :: Qt"),
    ("Framework____BFG", "Framework :: BFG"),
    ("Framework____Buildout", "Framework :: Buildout"),
    ("Framework____Buildout____Extension",
        "Framework :: Buildout :: Extension"),
    ("Framework____Buildout____Recipe", "Framework :: Buildout :: Recipe"),
    ("Framework____Chandler", "Framework :: Chandler"),
    ("Framework____CherryPy", "Framework :: CherryPy"),
    ("Framework____CubicWeb", "Framework :: CubicWeb"),
    ("Framework____Django", "Framework :: Django"),
    ("Framework____IDLE", "Framework :: IDLE"),
    ("Framework____Paste", "Framework :: Paste"),
    ("Framework____Plone", "Framework :: Plone"),
    ("Framework____Plone____3.2", "Framework :: Plone :: 3.2"),
    ("Framework____Plone____3.3", "Framework :: Plone :: 3.3"),
    ("Framework____Plone____4.0", "Framework :: Plone :: 4.0"),
    ("Framework____Plone____4.1", "Framework :: Plone :: 4.1"),
    ("Framework____Plone____4.2", "Framework :: Plone :: 4.2"),
    ("Framework____Plone____4.3", "Framework :: Plone :: 4.3"),
    ("Framework____Pylons", "Framework :: Pylons"),
    ("Framework____Setuptools_Plugin", "Framework :: Setuptools Plugin"),
    ("Framework____Trac", "Framework :: Trac"),
    ("Framework____Tryton", "Framework :: Tryton"),
    ("Framework____TurboGears", "Framework :: TurboGears"),
    ("Framework____TurboGears____Applications",
        "Framework :: TurboGears :: Applications"),
    ("Framework____TurboGears____Widgets",
        "Framework :: TurboGears :: Widgets"),
    ("Framework____Twisted", "Framework :: Twisted"),
    ("Framework____ZODB", "Framework :: ZODB"),
    ("Framework____Zope2", "Framework :: Zope2"),
    ("Framework____Zope3", "Framework :: Zope3"),
    ("Intended_Audience____Customer_Service",
        "Intended Audience :: Customer Service"),
    ("Intended_Audience____Developers", "Intended Audience :: Developers"),
    ("Intended_Audience____Education", "Intended Audience :: Education"),
    ("Intended_Audience____End_Users_Desktop",
        "Intended Audience :: End Users/Desktop"),
    ("Intended_Audience____Financial_and_Insurance_Industry",
        "Intended Audience :: Financial and Insurance Industry"),
    ("Intended_Audience____Healthcare_Industry",
        "Intended Audience :: Healthcare Industry"),
    ("Intended_Audience____Information_Technology",
        "Intended Audience :: Information Technology"),
    ("Intended_Audience____Legal_Industry",
        "Intended Audience :: Legal Industry"),
    ("Intended_Audience____Manufacturing",
        "Intended Audience :: Manufacturing"),
    ("Intended_Audience____Other_Audience",
        "Intended Audience :: Other Audience"),
    ("Intended_Audience____Religion",
        "Intended Audience :: Religion"),
    ("Intended_Audience____Science_Research",
        "Intended Audience :: Science/Research"),
    ("Intended_Audience____System_Administrators",
        "Intended Audience :: System Administrators"),
    ("Intended_Audience____Telecommunications_Industry",
        "Intended Audience :: Telecommunications Industry"),
    ("License____Aladdin_Free_Public_License_(AFPL)",
        "License :: Aladdin Free Public License (AFPL)"),
    ("License____CC0_1.0_Universal_(CC0_1.0)_Public_Domain_Dedication",
        "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication"),
    ("License____DFSG_approved", "License :: DFSG approved"),
    ("License____Eiffel_Forum_License_(EFL)",
        "License :: Eiffel Forum License (EFL)"),
    ("License____Free_For_Educational_Use",
        "License :: Free For Educational Use"),
    ("License____Free_For_Home_Use", "License :: Free For Home Use"),
    ("License____Free_for_non-commercial_use",
        "License :: Free for non-commercial use"),
    ("License____Freely_Distributable", "License :: Freely Distributable"),
    ("License____Free_To_Use_But_Restricted",
        "License :: Free To Use But Restricted"),
    ("License____Freeware",
        "License :: Freeware"),
    ("License____Netscape_Public_License_(NPL)",
        "License :: Netscape Public License (NPL)"),
    ("License____Nokia_Open_Source_License_(NOKOS)",
        "License :: Nokia Open Source License (NOKOS)"),
    ("License____OSI_Approved",
        "License :: OSI Approved"),
    ("License____OSI_Approved____Academic_Free_License_(AFL)",
        "License :: OSI Approved :: Academic Free License (AFL)"),
    ("License____OSI_Approved____Apache_Software_License",
        "License :: OSI Approved :: Apache Software License"),
    ("License____OSI_Approved____Apple_Public_Source_License",
        "License :: OSI Approved :: Apple Public Source License"),
    ("License____OSI_Approved____Artistic_License",
        "License :: OSI Approved :: Artistic License"),
    ("License____OSI_Approved____Attribution_Assurance_License",
        "License :: OSI Approved :: Attribution Assurance License"),
    ("License____OSI_Approved____BSD_License",
        "License :: OSI Approved :: BSD License"),
    ("License____OSI_Approved____Common_Public_License",
        "License :: OSI Approved :: Common Public License"),
    ("License____OSI_Approved____Eiffel_Forum_License",
        "License :: OSI Approved :: Eiffel Forum License"),
    ("License____OSI_Approved____European_Union_Public_Licence_1.0_(EUPL_1.0)",
        "License :: OSI Approved :: "
        "European Union Public Licence 1.0 (EUPL 1.0)"),
    ("License____OSI_Approved____European_Union_Public_Licence_1.1_(EUPL_1.1)",
        "License :: OSI Approved :: "
        "European Union Public Licence 1.1 (EUPL 1.1)"),
    ("License____OSI_Approved____GNU_Affero_General_Public_License_v3",
        "License :: OSI Approved :: GNU Affero General Public License v3"),
    ("License____OSI_Approved____GNU_Free_Documentation_License_(FDL)",
        "License :: OSI Approved :: GNU Free Documentation License (FDL)"),
    ("License____OSI_Approved____GNU_General_Public_License_(GPL)",
        "License :: OSI Approved :: GNU General Public License (GPL)"),
    ("License____OSI_Approved____"
        "GNU_Library_or_Lesser_General_Public_License_(LGPL)",
        "License :: OSI Approved :: "
        "GNU Library or Lesser General Public License (LGPL)"),
    ("License____OSI_Approved____IBM_Public_License",
        "License :: OSI Approved :: IBM Public License"),
    ("License____OSI_Approved____Intel_Open_Source_License",
        "License :: OSI Approved :: Intel Open Source License"),
    ("License____OSI_Approved____ISC_License_(ISCL)",
        "License :: OSI Approved :: ISC License (ISCL)"),
    ("License____OSI_Approved____Jabber_Open_Source_License",
        "License :: OSI Approved :: Jabber Open Source License"),
    ("License____OSI_Approved____MIT_License",
        "License :: OSI Approved :: MIT License"),
    ("License____OSI_Approved____"
        "MITRE_Collaborative_Virtual_Workspace_License_(CVW)",
        "License :: OSI Approved :: "
        "MITRE Collaborative Virtual Workspace License (CVW)"),
    ("License____OSI_Approved____Motosoto_License",
        "License :: OSI Approved :: Motosoto License"),
    ("License____OSI_Approved____Mozilla_Public_License_1.0_(MPL)",
        "License :: OSI Approved :: Mozilla Public License 1.0 (MPL)"),
    ("License____OSI_Approved____Mozilla_Public_License_1.1_(MPL_1.1)",
        "License :: OSI Approved :: Mozilla Public License 1.1 (MPL 1.1)"),
    ("License____OSI_Approved____Nethack_General_Public_License",
        "License :: OSI Approved :: Nethack General Public License"),
    ("License____OSI_Approved____Nokia_Open_Source_License",
        "License :: OSI Approved :: Nokia Open Source License"),
    ("License____OSI_Approved____Open_Group_Test_Suite_License",
        "License :: OSI Approved :: Open Group Test Suite License"),
    ("License____OSI_Approved____Python_License_(CNRI_Python_License)",
        "License :: OSI Approved :: Python License (CNRI Python License)"),
    ("License____OSI_Approved____Python_Software_Foundation_License",
        "License :: OSI Approved :: Python Software Foundation License"),
    ("License____OSI_Approved____Qt_Public_License_(QPL)",
        "License :: OSI Approved :: Qt Public License (QPL)"),
    ("License____OSI_Approved____Ricoh_Source_Code_Public_License",
        "License :: OSI Approved :: Ricoh Source Code Public License"),
    ("License____OSI_Approved____Sleepycat_License",
        "License :: OSI Approved :: Sleepycat License"),
    ("License____OSI_Approved____"
        "Sun_Industry_Standards_Source_License_(SISSL)",
        "License :: OSI Approved :: "
        "Sun Industry Standards Source License (SISSL)"),
    ("License____OSI_Approved____Sun_Public_License",
        "License :: OSI Approved :: Sun Public License"),
    ("License____OSI_Approved____"
        "University_of_Illinois/NCSA_Open_Source_License",
        "License :: OSI Approved :: "
        "University of Illinois/NCSA Open Source License"),
    ("License____OSI_Approved____Vovida_Software_License_1.0",
        "License :: OSI Approved :: Vovida Software License 1.0"),
    ("License____OSI_Approved____W3C_License",
        "License :: OSI Approved :: W3C License"),
    ("License____OSI_Approved____X.Net_License",
        "License :: OSI Approved :: X.Net License"),
    ("License____OSI_Approved____zlib/libpng_License",
        "License :: OSI Approved :: zlib/libpng License"),
    ("License____OSI_Approved____Zope_Public_License",
        "License :: OSI Approved :: Zope Public License"),
    ("License____Other/Proprietary_License",
        "License :: Other/Proprietary License"),
    ("License____Public_Domain",
        "License :: Public Domain"),
    ("License____Repoze_Public_License",
        "License :: Repoze Public License"),
    ("Natural_Language____Afrikaans",
        "Natural Language :: Afrikaans"),
    ("Natural_Language____Arabic",
        "Natural Language :: Arabic"),
    ("Natural_Language____Bengali",
        "Natural Language :: Bengali"),
    ("Natural_Language____Bosnian",
        "Natural Language :: Bosnian"),
    ("Natural_Language____Bulgarian",
        "Natural Language :: Bulgarian"),
    ("Natural_Language____Catalan",
        "Natural Language :: Catalan"),
    ("Natural_Language____Chinese_(Simplified)",
        "Natural Language :: Chinese (Simplified)"),
    ("Natural_Language____Chinese_(Traditional)",
        "Natural Language :: Chinese (Traditional)"),
    ("Natural_Language____Croatian",
        "Natural Language :: Croatian"),
    ("Natural_Language____Czech",
        "Natural Language :: Czech"),
    ("Natural_Language____Danish",
        "Natural Language :: Danish"),
    ("Natural_Language____Dutch",
        "Natural Language :: Dutch"),
    ("Natural_Language____English",
        "Natural Language :: English"),
    ("Natural_Language____Esperanto",
        "Natural Language :: Esperanto"),
    ("Natural_Language____Finnish",
        "Natural Language :: Finnish"),
    ("Natural_Language____French",
        "Natural Language :: French"),
    ("Natural_Language____German",
        "Natural Language :: German"),
    ("Natural_Language____Greek",
        "Natural Language :: Greek"),
    ("Natural_Language____Hebrew",
        "Natural Language :: Hebrew"),
    ("Natural_Language____Hindi",
        "Natural Language :: Hindi"),
    ("Natural_Language____Hungarian",
        "Natural Language :: Hungarian"),
    ("Natural_Language____Icelandic",
        "Natural Language :: Icelandic"),
    ("Natural_Language____Indonesian",
        "Natural Language :: Indonesian"),
    ("Natural_Language____Italian",
        "Natural Language :: Italian"),
    ("Natural_Language____Japanese",
        "Natural Language :: Japanese"),
    ("Natural_Language____Javanese",
        "Natural Language :: Javanese"),
    ("Natural_Language____Korean",
        "Natural Language :: Korean"),
    ("Natural_Language____Latin",
        "Natural Language :: Latin"),
    ("Natural_Language____Latvian",
        "Natural Language :: Latvian"),
    ("Natural_Language____Macedonian",
        "Natural Language :: Macedonian"),
    ("Natural_Language____Malay",
        "Natural Language :: Malay"),
    ("Natural_Language____Marathi",
        "Natural Language :: Marathi"),
    ("Natural_Language____Norwegian",
        "Natural Language :: Norwegian"),
    ("Natural_Language____Panjabi",
        "Natural Language :: Panjabi"),
    ("Natural_Language____Persian",
        "Natural Language :: Persian"),
    ("Natural_Language____Polish",
        "Natural Language :: Polish"),
    ("Natural_Language____Portuguese",
        "Natural Language :: Portuguese"),
    ("Natural_Language____Portuguese_(Brazilian)",
        "Natural Language :: Portuguese (Brazilian)"),
    ("Natural_Language____Romanian", "Natural Language :: Romanian"),
    ("Natural_Language____Russian", "Natural Language :: Russian"),
    ("Natural_Language____Serbian", "Natural Language :: Serbian"),
    ("Natural_Language____Slovak", "Natural Language :: Slovak"),
    ("Natural_Language____Slovenian", "Natural Language :: Slovenian"),
    ("Natural_Language____Spanish", "Natural Language :: Spanish"),
    ("Natural_Language____Swedish", "Natural Language :: Swedish"),
    ("Natural_Language____Tamil", "Natural Language :: Tamil"),
    ("Natural_Language____Telugu", "Natural Language :: Telugu"),
    ("Natural_Language____Thai", "Natural Language :: Thai"),
    ("Natural_Language____Turkish", "Natural Language :: Turkish"),
    ("Natural_Language____Ukranian", "Natural Language :: Ukranian"),
    ("Natural_Language____Urdu", "Natural Language :: Urdu"),
    ("Natural_Language____Vietnamese", "Natural Language :: Vietnamese"),
    ("Operating_System____BeOS", "Operating System :: BeOS"),
    ("Operating_System____MacOS",
        "Operating System :: MacOS"),
    ("Operating_System____MacOS____MacOS_9",
        "Operating System :: MacOS :: MacOS 9"),
    ("Operating_System____MacOS____MacOS_X",
        "Operating System :: MacOS :: MacOS X"),
    ("Operating_System____Microsoft",
        "Operating System :: Microsoft"),
    ("Operating_System____Microsoft____MS-DOS",
        "Operating System :: Microsoft :: MS-DOS"),
    ("Operating_System____Microsoft____Windows",
        "Operating System :: Microsoft :: Windows"),
    ("Operating_System____Microsoft____Windows____Windows_3.1_or_Earlier",
        "Operating System :: Microsoft :: Windows :: Windows 3.1 or Earlier"),
    ("Operating_System____Microsoft____Windows____Windows_95/98/2000",
        "Operating System :: Microsoft :: Windows :: Windows 95/98/2000"),
    ("Operating_System____Microsoft____Windows____Windows_CE",
        "Operating System :: Microsoft :: Windows :: Windows CE"),
    ("Operating_System____Microsoft____Windows____Windows_NT/2000",
        "Operating System :: Microsoft :: Windows :: Windows NT/2000"),
    ("Operating_System____OS_2",
        "Operating System :: OS/2"),
    ("Operating_System____OS_Independent",
        "Operating System :: OS Independent"),
    ("Operating_System____Other_OS",
        "Operating System :: Other OS"),
    ("Operating_System____PalmOS",
        "Operating System :: PalmOS"),
    ("Operating_System____PDA_Systems",
        "Operating System :: PDA Systems"),
    ("Operating_System____POSIX",
        "Operating System :: POSIX"),
    ("Operating_System____POSIX____AIX",
        "Operating System :: POSIX :: AIX"),
    ("Operating_System____POSIX____BSD",
        "Operating System :: POSIX :: BSD"),
    ("Operating_System____POSIX____BSD____BSD/OS",
        "Operating System :: POSIX :: BSD :: BSD/OS"),
    ("Operating_System____POSIX____BSD____FreeBSD",
        "Operating System :: POSIX :: BSD :: FreeBSD"),
    ("Operating_System____POSIX____BSD____NetBSD",
        "Operating System :: POSIX :: BSD :: NetBSD"),
    ("Operating_System____POSIX____BSD____OpenBSD",
        "Operating System :: POSIX :: BSD :: OpenBSD"),
    ("Operating_System____POSIX____GNU_Hurd",
        "Operating System :: POSIX :: GNU Hurd"),
    ("Operating_System____POSIX____HP-UX",
        "Operating System :: POSIX :: HP-UX"),
    ("Operating_System____POSIX____IRIX",
        "Operating System :: POSIX :: IRIX"),
    ("Operating_System____POSIX____Linux",
        "Operating System :: POSIX :: Linux"),
    ("Operating_System____POSIX____Other",
        "Operating System :: POSIX :: Other"),
    ("Operating_System____POSIX____SCO",
        "Operating System :: POSIX :: SCO"),
    ("Operating_System____POSIX____SunOS/Solaris",
        "Operating System :: POSIX :: SunOS/Solaris"),
    ("Operating_System____Unix",
        "Operating System :: Unix"),
    ("Programming_Language____Ada",
        "Programming Language :: Ada"),
    ("Programming_Language____APL",
        "Programming Language :: APL"),
    ("Programming_Language____ASP",
        "Programming Language :: ASP"),
    ("Programming_Language____Assembly",
        "Programming Language :: Assembly"),
    ("Programming_Language____Awk",
        "Programming Language :: Awk"),
    ("Programming_Language____Basic",
        "Programming Language :: Basic"),
    ("Programming_Language____C",
        "Programming Language :: C"),
    ("Programming_Language____C#",
        "Programming Language :: C#"),
    ("Programming_Language____C++",
        "Programming Language :: C++"),
    ("Programming_Language____Cold_Fusion",
        "Programming Language :: Cold Fusion"),
    ("Programming_Language____Cython",
        "Programming Language :: Cython"),
    ("Programming_Language____Delphi/Kylix",
        "Programming Language :: Delphi/Kylix"),
    ("Programming_Language____Dylan",
        "Programming Language :: Dylan"),
    ("Programming_Language____Eiffel",
        "Programming Language :: Eiffel"),
    ("Programming_Language____Emacs-Lisp",
        "Programming Language :: Emacs-Lisp"),
    ("Programming_Language____Erlang",
        "Programming Language :: Erlang"),
    ("Programming_Language____Euler",
        "Programming Language :: Euler"),
    ("Programming_Language____Euphoria",
        "Programming Language :: Euphoria"),
    ("Programming_Language____Forth",
        "Programming Language :: Forth"),
    ("Programming_Language____Fortran",
        "Programming Language :: Fortran"),
    ("Programming_Language____Haskell",
        "Programming Language :: Haskell"),
    ("Programming_Language____Java",
        "Programming Language :: Java"),
    ("Programming_Language____JavaScript",
        "Programming Language :: JavaScript"),
    ("Programming_Language____Lisp",
        "Programming Language :: Lisp"),
    ("Programming_Language____Logo",
        "Programming Language :: Logo"),
    ("Programming_Language____ML",
        "Programming Language :: ML"),
    ("Programming_Language____Modula",
        "Programming Language :: Modula"),
    ("Programming_Language____Objective_C",
        "Programming Language :: Objective C"),
    ("Programming_Language____Object_Pascal",
        "Programming Language :: Object Pascal"),
    ("Programming_Language____OCaml",
        "Programming Language :: OCaml"),
    ("Programming_Language____Other",
        "Programming Language :: Other"),
    ("Programming_Language____Other_Scripting_Engines",
        "Programming Language :: Other Scripting Engines"),
    ("Programming_Language____Pascal",
        "Programming Language :: Pascal"),
    ("Programming_Language____Perl",
        "Programming Language :: Perl"),
    ("Programming_Language____PHP",
        "Programming Language :: PHP"),
    ("Programming_Language____Pike",
        "Programming Language :: Pike"),
    ("Programming_Language____Pliant",
        "Programming Language :: Pliant"),
    ("Programming_Language____PL/SQL",
        "Programming Language :: PL/SQL"),
    ("Programming_Language____PROGRESS",
        "Programming Language :: PROGRESS"),
    ("Programming_Language____Prolog",
        "Programming Language :: Prolog"),
    ("Programming_Language____Python",
        "Programming Language :: Python"),
    ("Programming_Language____Python____2",
        "Programming Language :: Python :: 2"),
    ("Programming_Language____Python____2.3",
        "Programming Language :: Python :: 2.3"),
    ("Programming_Language____Python____2.4",
        "Programming Language :: Python :: 2.4"),
    ("Programming_Language____Python____2.5",
        "Programming Language :: Python :: 2.5"),
    ("Programming_Language____Python____2.6",
        "Programming Language :: Python :: 2.6"),
    ("Programming_Language____Python____2.7",
        "Programming Language :: Python :: 2.7"),
    ("Programming_Language____Python____3",
        "Programming Language :: Python :: 3"),
    ("Programming_Language____Python____3.0",
        "Programming Language :: Python :: 3.0"),
    ("Programming_Language____Python____3.1",
        "Programming Language :: Python :: 3.1"),
    ("Programming_Language____Python____3.2",
        "Programming Language :: Python :: 3.2"),
    ("Programming_Language____Python____Implementation",
        "Programming Language :: Python :: Implementation"),
    ("Programming_Language____Python____Implementation____CPython",
        "Programming Language :: Python :: Implementation :: CPython"),
    ("Programming_Language____Python____Implementation____IronPython",
        "Programming Language :: Python :: Implementation :: IronPython"),
    ("Programming_Language____Python____Implementation____Jython",
        "Programming Language :: Python :: Implementation :: Jython"),
    ("Programming_Language____Python____Implementation____PyPy",
        "Programming Language :: Python :: Implementation :: PyPy"),
    ("Programming_Language____Python____Implementation____Stackless",
        "Programming Language :: Python :: Implementation :: Stackless"),
    ("Programming_Language____REBOL", "Programming Language :: REBOL"),
    ("Programming_Language____Rexx", "Programming Language :: Rexx"),
    ("Programming_Language____Ruby", "Programming Language :: Ruby"),
    ("Programming_Language____Scheme", "Programming Language :: Scheme"),
    ("Programming_Language____Simula", "Programming Language :: Simula"),
    ("Programming_Language____Smalltalk", "Programming Language :: Smalltalk"),
    ("Programming_Language____SQL", "Programming Language :: SQL"),
    ("Programming_Language____Tcl", "Programming Language :: Tcl"),
    ("Programming_Language____Unix_Shell",
        "Programming Language :: Unix Shell"),
    ("Programming_Language____Visual_Basic",
        "Programming Language :: Visual Basic"),
    ("Programming_Language____XBasic", "Programming Language :: XBasic"),
    ("Programming_Language____YACC", "Programming Language :: YACC"),
    ("Programming_Language____Zope", "Programming Language :: Zope"),
    ("Topic____Adaptive_Technologies", "Topic :: Adaptive Technologies"),
    ("Topic____Artistic_Software", "Topic :: Artistic Software"),
    ("Topic____Communications", "Topic :: Communications"),
    ("Topic____Communications____BBS", "Topic :: Communications :: BBS"),
    ("Topic____Communications____Chat",
        "Topic :: Communications :: Chat"),
    ("Topic____Communications____Chat____AOL_Instant_Messenger",
        "Topic :: Communications :: Chat :: AOL Instant Messenger"),
    ("Topic____Communications____Chat____ICQ",
        "Topic :: Communications :: Chat :: ICQ"),
    ("Topic____Communications____Chat____Internet_Relay_Chat",
        "Topic :: Communications :: Chat :: Internet Relay Chat"),
    ("Topic____Communications____Chat____Unix_Talk",
        "Topic :: Communications :: Chat :: Unix Talk"),
    ("Topic____Communications____Conferencing",
        "Topic :: Communications :: Conferencing"),
    ("Topic____Communications____Email",
        "Topic :: Communications :: Email"),
    ("Topic____Communications____Email____Address_Book",
        "Topic :: Communications :: Email :: Address Book"),
    ("Topic____Communications____Email____Email_Clients_(MUA)",
        "Topic :: Communications :: Email :: Email Clients (MUA)"),
    ("Topic____Communications____Email____Filters",
        "Topic :: Communications :: Email :: Filters"),
    ("Topic____Communications____Email____Mailing_List_Servers",
        "Topic :: Communications :: Email :: Mailing List Servers"),
    ("Topic____Communications____Email____Mail_Transport_Agents",
        "Topic :: Communications :: Email :: Mail Transport Agents"),
    ("Topic____Communications____Email____Post-Office",
        "Topic :: Communications :: Email :: Post-Office"),
    ("Topic____Communications____Email____Post-Office____IMAP",
        "Topic :: Communications :: Email :: Post-Office :: IMAP"),
    ("Topic____Communications____Email____Post-Office____POP3",
        "Topic :: Communications :: Email :: Post-Office :: POP3"),
    ("Topic____Communications____Fax",
        "Topic :: Communications :: Fax"),
    ("Topic____Communications____FIDO",
        "Topic :: Communications :: FIDO"),
    ("Topic____Communications____File_Sharing",
        "Topic :: Communications :: File Sharing"),
    ("Topic____Communications____File_Sharing____Gnutella",
        "Topic :: Communications :: File Sharing :: Gnutella"),
    ("Topic____Communications____File_Sharing____Napster",
        "Topic :: Communications :: File Sharing :: Napster"),
    ("Topic____Communications____Ham_Radio",
        "Topic :: Communications :: Ham Radio"),
    ("Topic____Communications____Internet_Phone",
        "Topic :: Communications :: Internet Phone"),
    ("Topic____Communications____Telephony",
        "Topic :: Communications :: Telephony"),
    ("Topic____Communications____Usenet_News",
        "Topic :: Communications :: Usenet News"),
    ("Topic____Database",
        "Topic :: Database"),
    ("Topic____Database____Database_Engines/Servers",
        "Topic :: Database :: Database Engines/Servers"),
    ("Topic____Database____Front-Ends",
        "Topic :: Database :: Front-Ends"),
    ("Topic____Desktop_Environment",
        "Topic :: Desktop Environment"),
    ("Topic____Desktop_Environment____File_Managers",
        "Topic :: Desktop Environment :: File Managers"),
    ("Topic____Desktop_Environment____Gnome",
        "Topic :: Desktop Environment :: Gnome"),
    ("Topic____Desktop_Environment____GNUstep",
        "Topic :: Desktop Environment :: GNUstep"),
    ("Topic____Desktop_Environment____K_Desktop_Environment_(KDE)",
        "Topic :: Desktop Environment :: K Desktop Environment (KDE)"),
    ("Topic____Desktop_Environment____K_Desktop_Environment_(KDE)____Themes",
        "Topic :: Desktop Environment :: "
        "K Desktop Environment (KDE) :: Themes"),
    ("Topic____Desktop_Environment____PicoGUI",
        "Topic :: Desktop Environment :: PicoGUI"),
    ("Topic____Desktop_Environment____PicoGUI____Applications",
        "Topic :: Desktop Environment :: PicoGUI :: Applications"),
    ("Topic____Desktop_Environment____PicoGUI____Themes",
        "Topic :: Desktop Environment :: PicoGUI :: Themes"),
    ("Topic____Desktop_Environment____Screen_Savers",
        "Topic :: Desktop Environment :: Screen Savers"),
    ("Topic____Desktop_Environment____Window_Managers",
        "Topic :: Desktop Environment :: Window Managers"),
    ("Topic____Desktop_Environment____Window_Managers____Afterstep",
        "Topic :: Desktop Environment :: Window Managers :: Afterstep"),
    ("Topic____Desktop_Environment____Window_Managers____Afterstep____Themes",
        "Topic :: Desktop Environment :: "
        "Window Managers :: Afterstep :: Themes"),
    ("Topic____Desktop_Environment____Window_Managers____Applets",
        "Topic :: Desktop Environment :: Window Managers :: Applets"),
    ("Topic____Desktop_Environment____Window_Managers____Blackbox",
        "Topic :: Desktop Environment :: Window Managers :: Blackbox"),
    ("Topic____Desktop_Environment____Window_Managers____Blackbox____"
        "Themes",
        "Topic :: Desktop Environment :: Window Managers :: Blackbox :: "
        "Themes"),
    ("Topic____Desktop_Environment____Window_Managers____CTWM",
        "Topic :: Desktop Environment :: Window Managers :: CTWM"),
    ("Topic____Desktop_Environment____Window_Managers____CTWM____Themes",
        "Topic :: Desktop Environment :: Window Managers :: CTWM :: Themes"),
    ("Topic____Desktop_Environment____Window_Managers____Enlightenment",
        "Topic :: Desktop Environment :: Window Managers :: Enlightenment"),
    ("Topic____Desktop_Environment____Window_Managers____Enlightenment____"
        "Epplets",
        "Topic :: Desktop Environment :: Window Managers :: Enlightenment :: "
        "Epplets"),
    ("Topic____Desktop_Environment____Window_Managers____Enlightenment____"
        "Themes_DR15",
        "Topic :: Desktop Environment :: Window Managers :: Enlightenment :: "
        "Themes DR15"),
    ("Topic____Desktop_Environment____Window_Managers____Enlightenment____"
        "Themes_DR16",
        "Topic :: Desktop Environment :: Window Managers :: Enlightenment :: "
        "Themes DR16"),
    ("Topic____Desktop_Environment____Window_Managers____Enlightenment____"
        "Themes_DR17",
        "Topic :: Desktop Environment :: Window Managers :: Enlightenment :: "
        "Themes DR17"),
    ("Topic____Desktop_Environment____Window_Managers____Fluxbox",
        "Topic :: Desktop Environment :: Window Managers :: Fluxbox"),
    ("Topic____Desktop_Environment____Window_Managers____Fluxbox____Themes",
        "Topic :: Desktop Environment :: Window Managers :: Fluxbox :: "
        "Themes"),
    ("Topic____Desktop_Environment____Window_Managers____FVWM",
        "Topic :: Desktop Environment :: Window Managers :: FVWM"),
    ("Topic____Desktop_Environment____Window_Managers____FVWM____Themes",
        "Topic :: Desktop Environment :: Window Managers :: FVWM :: Themes"),
    ("Topic____Desktop_Environment____Window_Managers____IceWM",
        "Topic :: Desktop Environment :: Window Managers :: IceWM"),
    ("Topic____Desktop_Environment____Window_Managers____IceWM____Themes",
        "Topic :: Desktop Environment :: Window Managers :: IceWM :: Themes"),
    ("Topic____Desktop_Environment____Window_Managers____MetaCity",
        "Topic :: Desktop Environment :: Window Managers :: MetaCity"),
    ("Topic____Desktop_Environment____Window_Managers____MetaCity____Themes",
        "Topic :: Desktop Environment :: Window Managers :: MetaCity :: "
        "Themes"),
    ("Topic____Desktop_Environment____Window_Managers____Oroborus",
        "Topic :: Desktop Environment :: Window Managers :: Oroborus"),
    ("Topic____Desktop_Environment____Window_Managers____Oroborus____Themes",
        "Topic :: Desktop Environment :: Window Managers :: Oroborus :: "
        "Themes"),
    ("Topic____Desktop_Environment____Window_Managers____Sawfish",
        "Topic :: Desktop Environment :: Window Managers :: Sawfish"),
    ("Topic____Desktop_Environment____Window_Managers____Sawfish____"
        "Themes_0.30",
        "Topic :: Desktop Environment :: Window Managers :: Sawfish :: "
        "Themes 0.30"),
    ("Topic____Desktop_Environment____Window_Managers____Sawfish____"
        "Themes_pre-0.30",
        "Topic :: Desktop Environment :: Window Managers :: Sawfish :: "
        "Themes pre-0.30"),
    ("Topic____Desktop_Environment____Window_Managers____Waimea",
        "Topic :: Desktop Environment :: Window Managers :: Waimea"),
    ("Topic____Desktop_Environment____Window_Managers____Waimea____Themes",
        "Topic :: Desktop Environment :: Window Managers :: Waimea :: Themes"),
    ("Topic____Desktop_Environment____Window_Managers____Window_Maker",
        "Topic :: Desktop Environment :: Window Managers :: Window Maker"),
    ("Topic____Desktop_Environment____Window_Managers____Window_Maker____"
        "Applets",
        "Topic :: Desktop Environment :: Window Managers :: Window Maker :: "
        "Applets"),
    ("Topic____Desktop_Environment____Window_Managers____Window_Maker____"
        "Themes",
        "Topic :: Desktop Environment :: Window Managers :: Window Maker :: "
        "Themes"),
    ("Topic____Desktop_Environment____Window_Managers____XFCE",
        "Topic :: Desktop Environment :: Window Managers :: XFCE"),
    ("Topic____Desktop_Environment____Window_Managers____XFCE____Themes",
        "Topic :: Desktop Environment :: Window Managers :: XFCE :: Themes"),
    ("Topic____Documentation",
        "Topic :: Documentation"),
    ("Topic____Education",
        "Topic :: Education"),
    ("Topic____Education____Computer_Aided_Instruction_(CAI)",
        "Topic :: Education :: Computer Aided Instruction (CAI)"),
    ("Topic____Education____Testing",
        "Topic :: Education :: Testing"),
    ("Topic____Games_Entertainment",
        "Topic :: Games/Entertainment"),
    ("Topic____Games/Entertainment____Arcade",
        "Topic :: Games/Entertainment :: Arcade"),
    ("Topic____Games/Entertainment____Board_Games",
        "Topic :: Games/Entertainment :: Board Games"),
    ("Topic____Games/Entertainment____First_Person_Shooters",
        "Topic :: Games/Entertainment :: First Person Shooters"),
    ("Topic____Games/Entertainment____Fortune_Cookies",
        "Topic :: Games/Entertainment :: Fortune Cookies"),
    ("Topic____Games/Entertainment____Multi-User_Dungeons_(MUD)",
        "Topic :: Games/Entertainment :: Multi-User Dungeons (MUD)"),
    ("Topic____Games/Entertainment____Puzzle_Games",
        "Topic :: Games/Entertainment :: Puzzle Games"),
    ("Topic____Games/Entertainment____Real_Time_Strategy",
        "Topic :: Games/Entertainment :: Real Time Strategy"),
    ("Topic____Games/Entertainment____Role-Playing",
        "Topic :: Games/Entertainment :: Role-Playing"),
    ("Topic____Games/Entertainment____Side-Scrolling/Arcade_Games",
        "Topic :: Games/Entertainment :: Side-Scrolling/Arcade Games"),
    ("Topic____Games/Entertainment____Simulation",
        "Topic :: Games/Entertainment :: Simulation"),
    ("Topic____Games/Entertainment____Turn_Based_Strategy",
        "Topic :: Games/Entertainment :: Turn Based Strategy"),
    ("Topic____Home_Automation",
        "Topic :: Home Automation"),
    ("Topic____Internet",
        "Topic :: Internet"),
    ("Topic____Internet____File_Transfer_Protocol_(FTP)",
        "Topic :: Internet :: File Transfer Protocol (FTP)"),
    ("Topic____Internet____Finger",
        "Topic :: Internet :: Finger"),
    ("Topic____Internet____Log_Analysis",
        "Topic :: Internet :: Log Analysis"),
    ("Topic____Internet____Name_Service_(DNS)",
        "Topic :: Internet :: Name Service (DNS)"),
    ("Topic____Internet____Proxy_Servers",
        "Topic :: Internet :: Proxy Servers"),
    ("Topic____Internet____WAP",
        "Topic :: Internet :: WAP"),
    ("Topic____Internet____WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP"),
    ("Topic____Internet____WWW/HTTP____Browsers",
        "Topic :: Internet :: WWW/HTTP :: Browsers"),
    ("Topic____Internet____WWW/HTTP____Dynamic_Content",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content"),
    ("Topic____Internet____WWW/HTTP____Dynamic_Content____CGI_Tools/Libraries",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: "
        "CGI Tools/Libraries"),
    ("Topic____Internet____WWW/HTTP____Dynamic_Content____Message_Boards",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Message Boards"),
    ("Topic____Internet____WWW/HTTP____Dynamic_Content____News/Diary",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: News/Diary"),
    ("Topic____Internet____WWW/HTTP____Dynamic_Content____Page_Counters",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Page Counters"),
    ("Topic____Internet____WWW/HTTP____HTTP_Servers",
        "Topic :: Internet :: WWW/HTTP :: HTTP Servers"),
    ("Topic____Internet____WWW/HTTP____Indexing/Search",
        "Topic :: Internet :: WWW/HTTP :: Indexing/Search"),
    ("Topic____Internet____WWW/HTTP____Session",
        "Topic :: Internet :: WWW/HTTP :: Session"),
    ("Topic____Internet____WWW/HTTP____Site_Management",
        "Topic :: Internet :: WWW/HTTP :: Site Management"),
    ("Topic____Internet____WWW/HTTP____Site_Management____Link_Checking",
        "Topic :: Internet :: WWW/HTTP :: Site Management :: Link Checking"),
    ("Topic____Internet____WWW/HTTP____WSGI",
        "Topic :: Internet :: WWW/HTTP :: WSGI"),
    ("Topic____Internet____WWW/HTTP____WSGI____Application",
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"),
    ("Topic____Internet____WWW/HTTP____WSGI____Middleware",
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware"),
    ("Topic____Internet____WWW/HTTP____WSGI____Server",
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Server"),
    ("Topic____Internet____Z39.50",
        "Topic :: Internet :: Z39.50"),
    ("Topic____Multimedia",
        "Topic :: Multimedia"),
    ("Topic____Multimedia____Graphics",
        "Topic :: Multimedia :: Graphics"),
    ("Topic____Multimedia____Graphics____3D_Modeling",
        "Topic :: Multimedia :: Graphics :: 3D Modeling"),
    ("Topic____Multimedia____Graphics____3D_Rendering",
        "Topic :: Multimedia :: Graphics :: 3D Rendering"),
    ("Topic____Multimedia____Graphics____Capture",
        "Topic :: Multimedia :: Graphics :: Capture"),
    ("Topic____Multimedia____Graphics____Capture____Digital_Camera",
        "Topic :: Multimedia :: Graphics :: Capture :: Digital Camera"),
    ("Topic____Multimedia____Graphics____Capture____Scanners",
        "Topic :: Multimedia :: Graphics :: Capture :: Scanners"),
    ("Topic____Multimedia____Graphics____Capture____Screen_Capture",
        "Topic :: Multimedia :: Graphics :: Capture :: Screen Capture"),
    ("Topic____Multimedia____Graphics____Editors",
        "Topic :: Multimedia :: Graphics :: Editors"),
    ("Topic____Multimedia____Graphics____Editors____Raster-Based",
        "Topic :: Multimedia :: Graphics :: Editors :: Raster-Based"),
    ("Topic____Multimedia____Graphics____Editors____Vector-Based",
        "Topic :: Multimedia :: Graphics :: Editors :: Vector-Based"),
    ("Topic____Multimedia____Graphics____Graphics_Conversion",
        "Topic :: Multimedia :: Graphics :: Graphics Conversion"),
    ("Topic____Multimedia____Graphics____Presentation",
        "Topic :: Multimedia :: Graphics :: Presentation"),
    ("Topic____Multimedia____Graphics____Viewers",
        "Topic :: Multimedia :: Graphics :: Viewers"),
    ("Topic____Multimedia____Sound/Audio",
        "Topic :: Multimedia :: Sound/Audio"),
    ("Topic____Multimedia____Sound/Audio____Analysis",
        "Topic :: Multimedia :: Sound/Audio :: Analysis"),
    ("Topic____Multimedia____Sound/Audio____Capture/Recording",
        "Topic :: Multimedia :: Sound/Audio :: Capture/Recording"),
    ("Topic____Multimedia____Sound/Audio____CD_Audio",
        "Topic :: Multimedia :: Sound/Audio :: CD Audio"),
    ("Topic____Multimedia____Sound/Audio____CD_Audio____CD_Playing",
        "Topic :: Multimedia :: Sound/Audio :: CD Audio :: CD Playing"),
    ("Topic____Multimedia____Sound/Audio____CD_Audio____CD_Ripping",
        "Topic :: Multimedia :: Sound/Audio :: CD Audio :: CD Ripping"),
    ("Topic____Multimedia____Sound/Audio____CD_Audio____CD_Writing",
        "Topic :: Multimedia :: Sound/Audio :: CD Audio :: CD Writing"),
    ("Topic____Multimedia____Sound/Audio____Conversion",
        "Topic :: Multimedia :: Sound/Audio :: Conversion"),
    ("Topic____Multimedia____Sound/Audio____Editors",
        "Topic :: Multimedia :: Sound/Audio :: Editors"),
    ("Topic____Multimedia____Sound/Audio____MIDI",
        "Topic :: Multimedia :: Sound/Audio :: MIDI"),
    ("Topic____Multimedia____Sound/Audio____Mixers",
        "Topic :: Multimedia :: Sound/Audio :: Mixers"),
    ("Topic____Multimedia____Sound/Audio____Players",
        "Topic :: Multimedia :: Sound/Audio :: Players"),
    ("Topic____Multimedia____Sound/Audio____Players____MP3",
        "Topic :: Multimedia :: Sound/Audio :: Players :: MP3"),
    ("Topic____Multimedia____Sound/Audio____Sound_Synthesis",
        "Topic :: Multimedia :: Sound/Audio :: Sound Synthesis"),
    ("Topic____Multimedia____Sound/Audio____Speech",
        "Topic :: Multimedia :: Sound/Audio :: Speech"),
    ("Topic____Multimedia____Video",
        "Topic :: Multimedia :: Video"),
    ("Topic____Multimedia____Video____Capture",
        "Topic :: Multimedia :: Video :: Capture"),
    ("Topic____Multimedia____Video____Conversion",
        "Topic :: Multimedia :: Video :: Conversion"),
    ("Topic____Multimedia____Video____Display",
        "Topic :: Multimedia :: Video :: Display"),
    ("Topic____Multimedia____Video____Non-Linear_Editor",
        "Topic :: Multimedia :: Video :: Non-Linear Editor"),
    ("Topic____Office_Business",
        "Topic :: Office/Business"),
    ("Topic____Office/Business____Financial",
        "Topic :: Office/Business :: Financial"),
    ("Topic____Office/Business____Financial____Accounting",
        "Topic :: Office/Business :: Financial :: Accounting"),
    ("Topic____Office/Business____Financial____Investment",
        "Topic :: Office/Business :: Financial :: Investment"),
    ("Topic____Office/Business____Financial____Point-Of-Sale",
        "Topic :: Office/Business :: Financial :: Point-Of-Sale"),
    ("Topic____Office/Business____Financial____Spreadsheet",
        "Topic :: Office/Business :: Financial :: Spreadsheet"),
    ("Topic____Office/Business____Groupware",
        "Topic :: Office/Business :: Groupware"),
    ("Topic____Office/Business____News/Diary",
        "Topic :: Office/Business :: News/Diary"),
    ("Topic____Office/Business____Office_Suites",
        "Topic :: Office/Business :: Office Suites"),
    ("Topic____Office/Business____Scheduling",
        "Topic :: Office/Business :: Scheduling"),
    ("Topic____Other_Nonlisted_Topic",
        "Topic :: Other/Nonlisted Topic"),
    ("Topic____Printing",
        "Topic :: Printing"),
    ("Topic____Religion",
        "Topic :: Religion"),
    ("Topic____Scientific_Engineering",
        "Topic :: Scientific/Engineering"),
    ("Topic____Scientific/Engineering____Artificial_Intelligence",
        "Topic :: Scientific/Engineering :: Artificial Intelligence"),
    ("Topic____Scientific/Engineering____Artificial_Life",
        "Topic :: Scientific/Engineering :: Artificial Life"),
    ("Topic____Scientific/Engineering____Astronomy",
        "Topic :: Scientific/Engineering :: Astronomy"),
    ("Topic____Scientific/Engineering____Atmospheric_Science",
        "Topic :: Scientific/Engineering :: Atmospheric Science"),
    ("Topic____Scientific/Engineering____Bio-Informatics",
        "Topic :: Scientific/Engineering :: Bio-Informatics"),
    ("Topic____Scientific/Engineering____Chemistry",
        "Topic :: Scientific/Engineering :: Chemistry"),
    ("Topic____Scientific/Engineering____Electronic_Design_Automation_(EDA)",
        "Topic :: Scientific/Engineering :: "
        "Electronic Design Automation (EDA)"),
    ("Topic____Scientific/Engineering____GIS",
        "Topic :: Scientific/Engineering :: GIS"),
    ("Topic____Scientific/Engineering____Human_Machine_Interfaces",
        "Topic :: Scientific/Engineering :: Human Machine Interfaces"),
    ("Topic____Scientific/Engineering____Image_Recognition",
        "Topic :: Scientific/Engineering :: Image Recognition"),
    ("Topic____Scientific/Engineering____Information_Analysis",
        "Topic :: Scientific/Engineering :: Information Analysis"),
    ("Topic____Scientific/Engineering____Interface_Engine/Protocol_Translator",
        "Topic :: Scientific/Engineering :: "
        "Interface Engine/Protocol Translator"),
    ("Topic____Scientific/Engineering____Mathematics",
        "Topic :: Scientific/Engineering :: Mathematics"),
    ("Topic____Scientific/Engineering____Medical_Science_Apps.",
        "Topic :: Scientific/Engineering :: Medical Science Apps."),
    ("Topic____Scientific/Engineering____Physics",
        "Topic :: Scientific/Engineering :: Physics"),
    ("Topic____Scientific/Engineering____Visualization",
        "Topic :: Scientific/Engineering :: Visualization"),
    ("Topic____Security",
        "Topic :: Security"),
    ("Topic____Security____Cryptography",
        "Topic :: Security :: Cryptography"),
    ("Topic____Sociology",
        "Topic :: Sociology"),
    ("Topic____Sociology____Genealogy",
        "Topic :: Sociology :: Genealogy"),
    ("Topic____Sociology____History",
        "Topic :: Sociology :: History"),
    ("Topic____Software_Development",
        "Topic :: Software Development"),
    ("Topic____Software_Development____Assemblers",
        "Topic :: Software Development :: Assemblers"),
    ("Topic____Software_Development____Bug_Tracking",
        "Topic :: Software Development :: Bug Tracking"),
    ("Topic____Software_Development____Build_Tools",
        "Topic :: Software Development :: Build Tools"),
    ("Topic____Software_Development____Code_Generators",
        "Topic :: Software Development :: Code Generators"),
    ("Topic____Software_Development____Compilers",
        "Topic :: Software Development :: Compilers"),
    ("Topic____Software_Development____Debuggers",
        "Topic :: Software Development :: Debuggers"),
    ("Topic____Software_Development____Disassemblers",
        "Topic :: Software Development :: Disassemblers"),
    ("Topic____Software_Development____Documentation",
        "Topic :: Software Development :: Documentation"),
    ("Topic____Software_Development____Embedded_Systems",
        "Topic :: Software Development :: Embedded Systems"),
    ("Topic____Software_Development____Internationalization",
        "Topic :: Software Development :: Internationalization"),
    ("Topic____Software_Development____Interpreters",
        "Topic :: Software Development :: Interpreters"),
    ("Topic____Software_Development____Libraries",
        "Topic :: Software Development :: Libraries"),
    ("Topic____Software_Development____Libraries____Application_Frameworks",
        "Topic :: Software Development :: Libraries :: "
        "Application Frameworks"),
    ("Topic____Software_Development____Libraries____Java_Libraries",
        "Topic :: Software Development :: Libraries :: Java Libraries"),
    ("Topic____Software_Development____Libraries____Perl_Modules",
        "Topic :: Software Development :: Libraries :: Perl Modules"),
    ("Topic____Software_Development____Libraries____PHP_Classes",
        "Topic :: Software Development :: Libraries :: PHP Classes"),
    ("Topic____Software_Development____Libraries____Pike_Modules",
        "Topic :: Software Development :: Libraries :: Pike Modules"),
    ("Topic____Software_Development____Libraries____pygame",
        "Topic :: Software Development :: Libraries :: pygame"),
    ("Topic____Software_Development____Libraries____Python_Modules",
        "Topic :: Software Development :: Libraries :: Python Modules"),
    ("Topic____Software_Development____Libraries____Ruby_Modules",
        "Topic :: Software Development :: Libraries :: Ruby Modules"),
    ("Topic____Software_Development____Libraries____Tcl_Extensions",
        "Topic :: Software Development :: Libraries :: Tcl Extensions"),
    ("Topic____Software_Development____Localization",
        "Topic :: Software Development :: Localization"),
    ("Topic____Software_Development____Object_Brokering",
        "Topic :: Software Development :: Object Brokering"),
    ("Topic____Software_Development____Object_Brokering____CORBA",
        "Topic :: Software Development :: Object Brokering :: CORBA"),
    ("Topic____Software_Development____Pre-processors",
        "Topic :: Software Development :: Pre-processors"),
    ("Topic____Software_Development____Quality_Assurance",
        "Topic :: Software Development :: Quality Assurance"),
    ("Topic____Software_Development____Testing",
        "Topic :: Software Development :: Testing"),
    ("Topic____Software_Development____Testing____Traffic_Generation",
        "Topic :: Software Development :: Testing :: Traffic Generation"),
    ("Topic____Software_Development____User_Interfaces",
        "Topic :: Software Development :: User Interfaces"),
    ("Topic____Software_Development____Version_Control",
        "Topic :: Software Development :: Version Control"),
    ("Topic____Software_Development____Version_Control____CVS",
        "Topic :: Software Development :: Version Control :: CVS"),
    ("Topic____Software_Development____Version_Control____RCS",
        "Topic :: Software Development :: Version Control :: RCS"),
    ("Topic____Software_Development____Version_Control____SCCS",
        "Topic :: Software Development :: Version Control :: SCCS"),
    ("Topic____Software_Development____Widget_Sets",
        "Topic :: Software Development :: Widget Sets"),
    ("Topic____System",
        "Topic :: System"),
    ("Topic____System____Archiving",
        "Topic :: System :: Archiving"),
    ("Topic____System____Archiving____Backup",
        "Topic :: System :: Archiving :: Backup"),
    ("Topic____System____Archiving____Compression",
        "Topic :: System :: Archiving :: Compression"),
    ("Topic____System____Archiving____Mirroring",
        "Topic :: System :: Archiving :: Mirroring"),
    ("Topic____System____Archiving____Packaging",
        "Topic :: System :: Archiving :: Packaging"),
    ("Topic____System____Benchmark",
        "Topic :: System :: Benchmark"),
    ("Topic____System____Boot",
        "Topic :: System :: Boot"),
    ("Topic____System____Boot____Init",
        "Topic :: System :: Boot :: Init"),
    ("Topic____System____Clustering",
        "Topic :: System :: Clustering"),
    ("Topic____System____Console_Fonts",
        "Topic :: System :: Console Fonts"),
    ("Topic____System____Distributed_Computing",
        "Topic :: System :: Distributed Computing"),
    ("Topic____System____Emulators",
        "Topic :: System :: Emulators"),
    ("Topic____System____Filesystems",
        "Topic :: System :: Filesystems"),
    ("Topic____System____Hardware",
        "Topic :: System :: Hardware"),
    ("Topic____System____Hardware____Hardware_Drivers",
        "Topic :: System :: Hardware :: Hardware Drivers"),
    ("Topic____System____Hardware____Mainframes",
        "Topic :: System :: Hardware :: Mainframes"),
    ("Topic____System____Hardware____Symmetric_Multi-processing",
        "Topic :: System :: Hardware :: Symmetric Multi-processing"),
    ("Topic____System____Installation/Setup",
        "Topic :: System :: Installation/Setup"),
    ("Topic____System____Logging",
        "Topic :: System :: Logging"),
    ("Topic____System____Monitoring",
        "Topic :: System :: Monitoring"),
    ("Topic____System____Networking",
        "Topic :: System :: Networking"),
    ("Topic____System____Networking____Firewalls",
        "Topic :: System :: Networking :: Firewalls"),
    ("Topic____System____Networking____Monitoring",
        "Topic :: System :: Networking :: Monitoring"),
    ("Topic____System____Networking____Monitoring____Hardware_Watchdog",
        "Topic :: System :: Networking :: Monitoring :: Hardware Watchdog"),
    ("Topic____System____Networking____Time_Synchronization",
        "Topic :: System :: Networking :: Time Synchronization"),
    ("Topic____System____Operating_System",
        "Topic :: System :: Operating System"),
    ("Topic____System____Operating_System_Kernels",
        "Topic :: System :: Operating System Kernels"),
    ("Topic____System____Operating_System_Kernels____BSD",
        "Topic :: System :: Operating System Kernels :: BSD"),
    ("Topic____System____Operating_System_Kernels____GNU_Hurd",
        "Topic :: System :: Operating System Kernels :: GNU Hurd"),
    ("Topic____System____Operating_System_Kernels____Linux",
        "Topic :: System :: Operating System Kernels :: Linux"),
    ("Topic____System____Power_(UPS)",
        "Topic :: System :: Power (UPS)"),
    ("Topic____System____Recovery_Tools",
        "Topic :: System :: Recovery Tools"),
    ("Topic____System____Shells",
        "Topic :: System :: Shells"),
    ("Topic____System____Software_Distribution",
        "Topic :: System :: Software Distribution"),
    ("Topic____System____Systems_Administration",
        "Topic :: System :: Systems Administration"),
    ("Topic____System____Systems_Administration____Authentication/Directory",
        "Topic :: System :: Systems Administration :: "
        "Authentication/Directory"),
    ("Topic____System____Systems_Administration____"
        "Authentication/Directory____LDAP",
        "Topic :: System :: Systems Administration :: "
        "Authentication/Directory :: LDAP"),
    ("Topic____System____Systems_Administration____"
        "Authentication/Directory____NIS",
        "Topic :: System :: Systems Administration :: "
        "Authentication/Directory :: NIS"),
    ("Topic____System____System_Shells",
        "Topic :: System :: System Shells"),
    ("Topic____Terminals",
        "Topic :: Terminals"),
    ("Topic____Terminals____Serial",
        "Topic :: Terminals :: Serial"),
    ("Topic____Terminals____Telnet",
        "Topic :: Terminals :: Telnet"),
    ("Topic____Terminals____Terminal_Emulators/X_Terminals",
        "Topic :: Terminals :: Terminal Emulators/X Terminals"),
    ("Topic____Text_Editors",
        "Topic :: Text Editors"),
    ("Topic____Text_Editors____Documentation",
        "Topic :: Text Editors :: Documentation"),
    ("Topic____Text_Editors____Emacs",
        "Topic :: Text Editors :: Emacs"),
    ("Topic____Text_Editors____Integrated_Development_Environments_(IDE)",
        "Topic :: Text Editors :: Integrated Development Environments (IDE)"),
    ("Topic____Text_Editors____Text_Processing",
        "Topic :: Text Editors :: Text Processing"),
    ("Topic____Text_Editors____Word_Processors",
        "Topic :: Text Editors :: Word Processors"),
    ("Topic____Text_Processing",
        "Topic :: Text Processing"),
    ("Topic____Text_Processing____Filters",
        "Topic :: Text Processing :: Filters"),
    ("Topic____Text_Processing____Fonts",
        "Topic :: Text Processing :: Fonts"),
    ("Topic____Text_Processing____General",
        "Topic :: Text Processing :: General"),
    ("Topic____Text_Processing____Indexing",
        "Topic :: Text Processing :: Indexing"),
    ("Topic____Text_Processing____Linguistic",
        "Topic :: Text Processing :: Linguistic"),
    ("Topic____Text_Processing____Markup",
        "Topic :: Text Processing :: Markup"),
    ("Topic____Text_Processing____Markup____HTML",
        "Topic :: Text Processing :: Markup :: HTML"),
    ("Topic____Text_Processing____Markup____LaTeX",
        "Topic :: Text Processing :: Markup :: LaTeX"),
    ("Topic____Text_Processing____Markup____SGML",
        "Topic :: Text Processing :: Markup :: SGML"),
    ("Topic____Text_Processing____Markup____VRML",
        "Topic :: Text Processing :: Markup :: VRML"),
    ("Topic____Text_Processing____Markup____XML",
        "Topic :: Text Processing :: Markup :: XML"),
    ("Topic____Utilities", "Topic :: Utilities"),
)

colors = {
    "Development Status": ('white', '#46a546'),
    "Environment": ('white', 'black'),
    "Framework": ('white', '#049cdb'),
    "Intended Audience": ('black', 'gray'),
    "License": ('black', '#f89406'),
    "Natural Language": ('white', '#9d261d'),
    "Operating System": ('black', '#ffc40d'),
    "Programming Language": ('white', '#c3325f'),
    "Topic": ('white', '#7a43b6'),
}
